name: ecommerce
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
 
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_margin_widget: ^0.0.3
  flutter_offline: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  persistent_bottom_nav_bar: ^5.0.2
  persistent_bottom_nav_bar_v2: ^4.2.8
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
 
  assets:
    - assets/images/
 
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
 